project_id = "aybapkhmgoeogjjgvjlb"

[functions.ai-search]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.calculate-lead-score]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.send-quote-notification]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-offer-notification]
verify_jwt = false

[functions.send-timecard-notification]
verify_jwt = false

[functions.send-sell-notification]
verify_jwt = false

[functions.send-helium-quote-notification]
verify_jwt = false

[functions.send-cryogenic-quote-notification]
verify_jwt = false
